version: '2'
services:
  nginx:
    #image: codefornl/<TODO> image has not been set
    build: carto-nginx-docker
    ports:
      - 80:80
    depends_on:
      - editor
      - sql-api
      - maps-api
  db:
    build: carto-postgis-docker
    # need to update cartodb extension
    # image: codefornl/carto-postgis
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
  box:
    image: busybox
    volumes:
      # Warning! Make sure you have a directory bundle_cache relative to docker-compose.yml
      - ./bundle_cache:/bundle_cache
      # Warning! Make sure you have a directory assets relative to docker-compose.yml
      - ./assets:/carto/public/assets
  maps-api:
    build: carto-maps-api-docker
    #image: codefornl/carto-maps-api-docker
    depends_on:
      - db
      - redis
    expose:
      - 8181
  sql-api:
    build: carto-sql-api-docker
    #image: codefornl/carto-sql-api
    environment:
      - POSTGRES_PASSWORD="password"
    depends_on:
      - db
      - redis
    expose:
      - 8080
  editor:
    build: carto-editor-docker
    #image: codefornl/carto-editor-docker
    environment:
      - BUNDLE_PATH=/bundle_cache
    depends_on:
      - sql-api
      - maps-api
      - db
      - redis
    volumes_from:
      - box
    expose:
      - 3000
    ports:
      - 3000:3000
